name: Release

on:
  push:
    tags:
      - 'v*.*.*'

env:
  IMAGE_REPO: ${{ secrets.DOCKERHUB_USERNAME }}/frontend

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install deps
        run: npm ci

      - name: Lint (optional)
        run: npm run lint --if-present

      - name: Test
        run: npm test -- --watch=false --browsers=ChromeHeadless
        env:
          CI: "true"

      - name: Build Angular (production)
        run: npm run build -- --configuration production

  build:
    runs-on: ubuntu-latest
    needs: test
    environment: prod

    steps:
      - uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          IMAGE_TAG=${GITHUB_REF#refs/tags/}
          echo "Building image with tag $IMAGE_TAG"
          docker build -t $IMAGE_REPO:$IMAGE_TAG .
          docker push $IMAGE_REPO:$IMAGE_TAG

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: prod

    steps:
      - name: Setup kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBE_CONFIG_PROD }}" | base64 --decode > $HOME/.kube/config

      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.4

      - name: Checkout Helm repo
        uses: actions/checkout@v4
        with:
          repository: APSList/Hostflow
          path: Hostflow
          token: ${{ secrets.GH_TOKEN }}

      - name: Deploy FRONTEND to PROD with Helm
        run: |
          IMAGE_TAG=${GITHUB_REF#refs/tags/}

          helm upgrade --install payment-frontend-prod ./Hostflow/helm/charts/frontend \
            --namespace prod \
            --create-namespace \
            --set image.repository=$IMAGE_REPO \
            --set image.tag=$IMAGE_TAG \
            --set image.pullPolicy=Always
